# name=input("Enter your name :")
# sirname=input("Enter your sirname :")
# age=input("Enter your age :")
# hobbies=input ("your hobbies :")
# print(name)
# print(sirname)
# print(age)
# print(hobbies)

# print(type(name))
# print(type(age))
# print(type(sirname))
# print(type(hobbies))
# print(id(name))
name = input("Enter your name :")
print("your name is "+name)
